// ============================================================================
// Pre-loaded game list from aukspot's dles (693 games as of 2026-04-27)
// ============================================================================
export const SEED_GAMES = [
    // Card/Board Games
    { name: "Chess.com Daily Puzzle", url: "https://www.chess.com/daily-chess-puzzle", category: "Card/Board" },
    { name: "Chessguessr", url: "https://www.chessguessr.com", category: "Card/Board" },
    { name: "Chessle", url: "https://jackli.gg/chessle", category: "Card/Board" },
    { name: "Echo Chess", url: "https://echochess.com", category: "Card/Board" },
    { name: "Enchant Worldle", url: "https://enchantworldle.com", category: "Card/Board" },
    { name: "Kickoff League", url: "https://kickoffleague.com", category: "Card/Board" },
    { name: "lichess.org Daily Puzzle", url: "https://lichess.org/training/daily", category: "Card/Board" },
    { name: "Mahjong Handle", url: "https://mahjong-handle.update.sh", category: "Card/Board" },
    { name: "Matle", url: "https://www.matle.io", category: "Card/Board" },
    { name: "Pokle", url: "https://poklegame.com", category: "Card/Board" },
    { name: "Puzzmo - Pile-Up Poker", url: "https://www.puzzmo.com/play/pile-up-poker", category: "Card/Board" },
    { name: "Puzzmo - Really Bad Chess", url: "https://www.puzzmo.com/play/really-bad-chess", category: "Card/Board" },
    { name: "Ronin", url: "https://www.andrewt.net/puzzles/ronin/", category: "Card/Board" },
    { name: "Royal Family", url: "https://coffeefirst.games/royal-family", category: "Card/Board" },
    { name: "Scrokkdle", url: "https://scrokkle.io/daily", category: "Card/Board" },
    { name: "Spellify", url: "https://edhrec.com/games/spellify", category: "Card/Board" },
    { name: "Sudoker", url: "https://sudoker.io", category: "Card/Board" },
    { name: "Takes", url: "https://takes.clevergoat.com", category: "Card/Board" },
    { name: "YGOdle", url: "https://www.ygodle.net/", category: "Card/Board" },
    { name: "Zaku Chess", url: "https://zakuchess.com", category: "Card/Board" },

    // Colors
    { name: "Chroma", url: "https://robson.plus/chroma", category: "Colors" },
    { name: "Colordle", url: "https://colordle.ryantanen.com", category: "Colors" },
    { name: "Colorfle", url: "https://colorfle.com", category: "Colors" },
    { name: "ColorGuesser", url: "https://colorguesser.com", category: "Colors" },
    { name: "Crayondle", url: "https://crayondle.com", category: "Colors" },
    { name: "Dialed - Color Game", url: "https://dialed.gg", category: "Colors" },
    { name: "Hexcodle", url: "https://www.hexcodle.com", category: "Colors" },
    { name: "Hexcodle Mini", url: "https://www.hexcodle.com/mini", category: "Colors" },

    // Estimation
    { name: "Amountle", url: "https://amountle.dev", category: "Estimation" },
    { name: "Angle", url: "https://angle.wtf", category: "Estimation" },
    { name: "Brickdle", url: "https://www.brickdle.com", category: "Estimation" },
    { name: "Centroid", url: "https://centroidgame.com", category: "Estimation" },
    { name: "Costcodle", url: "https://costcodle.com", category: "Estimation" },
    { name: "Cutle", url: "https://pfiffel.com/cutle/", category: "Estimation" },
    { name: "Estimadle", url: "https://estimadle.com", category: "Estimation" },
    { name: "Estimate Me", url: "https://estimate-me.aukspot.com", category: "Estimation" },
    { name: "Far Out", url: "https://www.faroutquiz.com", category: "Estimation" },
    { name: "Guess The Angle", url: "https://guesstheangle.wtf", category: "Estimation" },
    { name: "Guess The House", url: "https://guessthe.house", category: "Estimation" },
    { name: "Housle", url: "https://housle.house", category: "Estimation" },
    { name: "More/Less", url: "https://lessgames.com/moreless", category: "Estimation" },
    { name: "Numblino", url: "https://numblino.com", category: "Estimation" },
    { name: "Packle", url: "https://packle.top", category: "Estimation" },
    { name: "Temple", url: "https://tck.mn/temple", category: "Estimation" },
    { name: "Timingle", url: "https://timingle.com", category: "Estimation" },
    { name: "Zonday", url: "https://zonday.app", category: "Estimation" },

    // Food
    { name: "Breadle", url: "https://breadle.us", category: "Food" },
    { name: "Curdle", url: "https://gumbo.systems/curdle/", category: "Food" },
    { name: "Daily Rinds", url: "https://dailyrinds.com", category: "Food" },
    { name: "FoodGuessr", url: "https://www.foodguessr.com", category: "Food" },
    { name: "Scrandle", url: "https://scrandle.com", category: "Food" },

    // Geography
    { name: "Ballot Blocks", url: "https://ballotblocks.com", category: "Geography" },
    { name: "BallotGuessr", url: "https://ballotguessr.com/daily", category: "Geography" },
    { name: "Chartle", url: "https://chartle.cc", category: "Geography" },
    { name: "Countryle", url: "https://www.countryle.com", category: "Geography" },
    { name: "Electle", url: "https://electle.fun", category: "Geography" },
    { name: "Flagdle", url: "https://www.flagdle.org", category: "Geography" },
    { name: "Flagdoku", url: "https://flagdoku.com", category: "Geography" },
    { name: "Flagged", url: "https://gamebunny.app/flagged", category: "Geography" },
    { name: "Flagle", url: "https://www.flagle.io", category: "Geography" },
    { name: "Flagle Game", url: "https://flagle-game.com", category: "Geography" },
    { name: "Flags Game", url: "https://flagsgame.net", category: "Geography" },
    { name: "GeoConnections", url: "https://geoconnections.net", category: "Geography" },
    { name: "Geodle", url: "https://geodle.me", category: "Geography" },
    { name: "Geografind", url: "https://coffeefirst.games/geografind", category: "Geography" },
    { name: "GeoGrid", url: "https://www.geogridgame.com", category: "Geography" },
    { name: "Geonections", url: "https://geonections.com", category: "Geography" },
    { name: "GeoQuest", url: "https://geoquest.gg", category: "Geography" },
    { name: "Globeiku", url: "https://www.globeiku.com", category: "Geography" },
    { name: "Globle", url: "https://globle-game.com/game", category: "Geography" },
    { name: "Globle Capitals", url: "https://globle-capitals.com", category: "Geography" },
    { name: "Juxtastat", url: "https://urbanstats.org/quiz.html", category: "Geography" },
    { name: "Landmarkd", url: "https://www.landmarkdgame.com", category: "Geography" },
    { name: "Locatle", url: "https://locatle.strct.net", category: "Geography" },
    { name: "MapGame", url: "https://mapgame.net", category: "MapGame" },
    { name: "Mapster", url: "https://mapster.teuteuf.fr", category: "Geography" },
    { name: "MapTap", url: "https://maptap.gg", category: "Geography" },
    { name: "Neighborle", url: "https://neighborle.com", category: "Geography" },
    { name: "OEC Connectrade", url: "https://oec.world/en/games/connectrade", category: "Geography" },
    { name: "OEC Pick 5", url: "https://oec.world/en/games/pick-5", category: "Geography" },
    { name: "OEC Tradle", url: "https://oec.world/en/games/tradle", category: "Geography" },
    { name: "Satle", url: "https://satle.ca", category: "Geography" },
    { name: "SatPin", url: "https://satpixel.com/en/satellite-pin-guess/", category: "Geography" },
    { name: "SatZoom", url: "https://satpixel.com/en/satellite-zoom-game/", category: "Geography" },
    { name: "Seadle", url: "https://seadle.muhashi.com", category: "Geography" },
    { name: "Statele", url: "https://statele.teuteuf.fr", category: "Geography" },
    { name: "TimeGuessr", url: "https://timeguessr.com", category: "Geography" },
    { name: "travle", url: "https://travle.earth", category: "Geography" },
    { name: "Treasure Guessr", url: "https://play.treasureguessr.com", category: "Geography" },
    { name: "Viewdle", url: "https://viewdle.org", category: "Geography" },
    { name: "WhenTaken", url: "https://whentaken.com", category: "Geography" },
    { name: "WhenTaken Movies", url: "https://movies.whentaken.com", category: "Geography" },
    { name: "WhereTaken", url: "https://wheretaken.teuteuf.fr", category: "Geography" },
    { name: "WhereTaken USA", url: "https://wheretakenusa.teuteuf.fr", category: "Geography" },
    { name: "WhichWay", url: "https://whichway.is", category: "Geography" },
    { name: "Worldle", url: "https://worldle.teuteuf.fr", category: "Geography" },

    // History
    { name: "Chronle", url: "https://chronle.com", category: "History" },
    { name: "Chrono", url: "https://chrono.quest", category: "History" },
    { name: "Chrono USA", url: "https://chrono.quest/us_history.html", category: "History" },
    { name: "Chronoodle", url: "https://chronoodle.com", category: "History" },
    { name: "Chronophoto", url: "https://www.chronophoto.app", category: "History" },
    { name: "Daydle", url: "https://daydle.com", category: "History" },
    { name: "Historydle", url: "https://historydle.com", category: "History" },
    { name: "Past Puzzle", url: "https://www.pastpuzzle.de", category: "History" },
    { name: "Ripple", url: "https://ripplegame.app", category: "History" },
    { name: "Sortwise", url: "https://sortwise.fun", category: "History" },
    { name: "Timdle", url: "https://www.timdle.com", category: "History" },
    { name: "Timeline", url: "https://timeline.fromthethink.com", category: "History" },
    { name: "TimeLine Game", url: "https://www.playtimelines.com", category: "History" },
    { name: "TimeSwipe", url: "https://play.timeswipe.fun", category: "History" },
    { name: "Which year", url: "https://whichyr.com", category: "History" },
    { name: "Yeardle", url: "https://histordle.com/yeardle", category: "History" },
    { name: "Yearly Daily", url: "https://coffeefirst.games/yearly-daily", category: "History" },

    // Math/Logic
    { name: "3Doku", url: "https://www.andrewt.net/puzzles/3doku/", category: "Math/Logic" },
    { name: "Bells & Whistles", url: "https://puzzmallow.com/bells", category: "Math/Logic" },
    { name: "BrainBashers Daily 30 Seconds", url: "https://www.brainbashers.com/30seconds.asp", category: "Math/Logic" },
    { name: "BrainBashers Daily Puzzle", url: "https://www.brainbashers.com/dailypuzzle.asp", category: "Math/Logic" },
    { name: "Buzzled", url: "https://puzzmallow.com/buzzled", category: "Math/Logic" },
    { name: "Calcle", url: "https://calclegame.com", category: "Math/Logic" },
    { name: "Cancelwise", url: "https://cancelwise.com", category: "Math/Logic" },
    { name: "Circle Moon Puzzles", url: "https://circle9puzzle.com", category: "Math/Logic" },
    { name: "Clue Raider", url: "https://clueraider.com", category: "Math/Logic" },
    { name: "Clues By Sam", url: "https://cluesbysam.com", category: "Math/Logic" },
    { name: "Cracked Sudoku", url: "https://danielchasehooper.com/projects/cracked-sudoku/", category: "Math/Logic" },
    { name: "Daily Akari", url: "https://dailyakari.com", category: "Math/Logic" },
    { name: "Dimension Flux", url: "https://dimensionflux.com", category: "Math/Logic" },
    { name: "Dodeku", url: "https://dodeku.com", category: "Math/Logic" },
    { name: "Domino Fit", url: "https://dominofit.isotropic.us", category: "Math/Logic" },
    { name: "Equations", url: "https://www.equations-game.com", category: "Math/Logic" },
    { name: "Fields", url: "https://inkwellgames.com/games/fields", category: "Math/Logic" },
    { name: "Figure", url: "https://figure.game", category: "Math/Logic" },
    { name: "Five Fold", url: "https://fivefold.ca", category: "Math/Logic" },
    { name: "Knotilus", url: "https://knotil.us", category: "Math/Logic" },
    { name: "Kuromasu", url: "https://nibble.games/kuromasu/kuromasu-small.html", category: "Math/Logic" },
    { name: "LA Times Sudoku", url: "https://www.latimes.com/games/sudoku", category: "Math/Logic" },
    { name: "LinkedIn - Mini Sudoku", url: "https://www.linkedin.com/games/mini-sudoku/", category: "Math/Logic" },
    { name: "LinkedIn - Queens", url: "https://www.linkedin.com/games/queens", category: "Math/Logic" },
    { name: "LinkedIn - Tango", url: "https://www.linkedin.com/games/tango", category: "Math/Logic" },
    { name: "Logiquiz", url: "https://www.logiquiz.com", category: "Math/Logic" },
    { name: "Mathdle", url: "https://mathdle.app", category: "Math/Logic" },
    { name: "Mathler", url: "https://www.mathler.com", category: "Math/Logic" },
    { name: "Mazele", url: "https://mazele.io", category: "Math/Logic" },
    { name: "Mineswifter", url: "https://mineswifter.com", category: "Math/Logic" },
    { name: "Murdle", url: "https://murdle.com", category: "Math/Logic" },
    { name: "Nerdle", url: "https://nerdlegame.com", category: "Math/Logic" },
    { name: "Netflix - Starstruck", url: "https://www.netflix.com/tudum/puzzled/starstruck/daily", category: "Math/Logic" },
    { name: "Netflix - Sudoku", url: "https://www.netflix.com/tudum/puzzled/sudoku/daily", category: "Math/Logic" },
    { name: "NextUp", url: "https://nextupgame.com", category: "Math/Logic" },
    { name: "Noggle", url: "https://nibble.games/noggle/noggle.html", category: "Math/Logic" },
    { name: "NonoDaily", url: "https://www.nonodaily.com", category: "Math/Logic" },
    { name: "Nonodle", url: "https://lab174.com/nonodle", category: "Math/Logic" },
    { name: "Number Island", url: "https://numberisland.com", category: "Math/Logic" },
    { name: "Numble", url: "https://numble.wtf", category: "Math/Logic" },
    { name: "Numbobulate", url: "https://www.numbobulate.com", category: "Math/Logic" },
    { name: "NYT Pips", url: "https://www.nytimes.com/games/pips", category: "Math/Logic" },
    { name: "NYT Sudoku", url: "https://www.nytimes.com/puzzles/sudoku", category: "Math/Logic" },
    { name: "One Up Puzzle", url: "https://www.oneuppuzzle.com", category: "Math/Logic" },
    { name: "Ophex", url: "https://www.andrewt.net/puzzles/ophex/", category: "Math/Logic" },
    { name: "Padlock", url: "https://www.padlockgame.net", category: "Math/Logic" },
    { name: "Parlorbox", url: "https://parlorbox.com/", category: "Math/Logic" },
    { name: "Pell Puzzles", url: "https://pell.achromath.com", category: "Math/Logic" },
    { name: "Pivots", url: "https://playpivots.com", category: "Math/Logic" },
    { name: "Primel", url: "https://converged.yt/primel", category: "Math/Logic" },
    { name: "Puzzmo - Memoku", url: "https://www.puzzmo.com/play/memoku", category: "Math/Logic" },
    { name: "Puzzmo - Weather Memoku", url: "https://www.puzzmo.com/play/weather-memoku", category: "Math/Logic" },
    { name: "QueenSweep", url: "https://playqueensweep.com", category: "Math/Logic" },
    { name: "Refiner", url: "https://nibble.games/refiner/", category: "Math/Logic" },
    { name: "regexle.com", url: "https://regexle.com", category: "Math/Logic" },
    { name: "Sequences", url: "https://www.dailyfastgames.com/#/sequences", category: "Math/Logic" },
    { name: "Shikaku of the day", url: "https://shikakuofthe.day", category: "Math/Logic" },
    { name: "Stars", url: "https://inkwellgames.com/games/stars", category: "Math/Logic" },
    { name: "Sudoku Shift", url: "https://coffeefirst.games/sudoku-shift/", category: "Math/Logic" },
    { name: "Summle", url: "https://summle.net", category: "Math/Logic" },
    { name: "Sumplete", url: "https://sumplete.com/daily", category: "Math/Logic" },
    { name: "Tally Game", url: "https://tally-game.com", category: "Math/Logic" },
    { name: "Terraformation", url: "https://puzzmallow.com/terraformation", category: "Math/Logic" },
    { name: "Tile Knight", url: "https://tileknight.com", category: "Math/Logic" },
    { name: "xdle", url: "https://zaratustra.itch.io/xdle", category: "Math/Logic" },
    { name: "Zebra Puzzles", url: "https://www.zebrapuzzles.com", category: "Math/Logic" },

    // Movies/TV
    { name: "Actorle", url: "https://actorle.com", category: "Movies/TV" },
    { name: "Actorle - Fill The Grid", url: "https://actorle.com/fill-the-grid", category: "Movies/TV" },
    { name: "Actorle - Storyboard", url: "https://actorle.com/storyboard", category: "Movies/TV" },
    { name: "Actorle TV", url: "https://actorle.tv", category: "Movies/TV" },
    { name: "Anidle", url: "https://anidle.net", category: "Movies/TV" },
    { name: "AniGuessr", url: "https://aniguessr.com", category: "Movies/TV" },
    { name: "Animdle", url: "https://animdle.com", category: "Movies/TV" },
    { name: "Avatardle", url: "https://avatardle.com", category: "Movies/TV" },
    { name: "BingeWatcher", url: "https://bingewatcher.org", category: "Movies/TV" },
    { name: "Box Office Game", url: "https://boxofficega.me", category: "Movies/TV" },
    { name: "Cartoonguessr", url: "https://cartoonguesser.pythonanywhere.com", category: "Movies/TV" },
    { name: "Cine2Nerdle", url: "https://www.cinenerdle2.app", category: "Movies/TV" },
    { name: "CineLine", url: "https://www.playcineline.com", category: "Movies/TV" },
    { name: "Cinema Circuit", url: "https://www.wfhgames.com/cinema-circuit", category: "Movies/TV" },
    { name: "Cinematrix", url: "https://www.vulture.com/article/daily-movie-grid-trivia-game-cinematrix.html", category: "Movies/TV" },
    { name: "Cliffhanger", url: "https://jumoh.com/games/cliffhanger/", category: "Movies/TV" },
    { name: "Emoji Quiz - Movies", url: "https://www.emojiquiz.net/movies", category: "Movies/TV" },
    { name: "Emoji Quiz - TV", url: "https://www.emojiquiz.net/tv", category: "Movies/TV" },
    { name: "faces", url: "https://faces.wtf", category: "Movies/TV" },
    { name: "Flickle", url: "https://flickle.app", category: "Movies/TV" },
    { name: "Framed", url: "https://framed.wtf", category: "Movies/TV" },
    { name: "Gaps", url: "https://gaps.wtf", category: "Movies/TV" },
    { name: "Giffle - Friends", url: "https://giffle.com/friends/", category: "Movies/TV" },
    { name: "Giffle - Simpsons", url: "https://giffle.com/simpsons/", category: "Movies/TV" },
    { name: "Guess The Movie", url: "https://guessthemovie.name", category: "Movies/TV" },
    { name: "Harrypotterdle", url: "https://www.harrypotterdle.com", category: "Movies/TV" },
    { name: "Jojodle", url: "https://www.jojodle.app", category: "Movies/TV" },
    { name: "Marveldle", url: "https://marveldle.com/character/audiovisual/guess", category: "Movies/TV" },
    { name: "Movie Grid", url: "https://moviegrid.io", category: "Movies/TV" },
    { name: "Movie Pyramid", url: "https://moviepyramid.io", category: "Movies/TV" },
    { name: "Movie Reveal", url: "https://moviereveal.io", category: "Movies/TV" },
    { name: "Movie Snake", url: "https://moviesnake.io", category: "Movies/TV" },
    { name: "Movie to Movie", url: "https://movietomovie.com", category: "Movies/TV" },
    { name: "Moviedle", url: "https://moviedle.xyz", category: "Movies/TV" },
    { name: "Moviedle (from Histordle)", url: "https://histordle.com/moviedle", category: "Movies/TV" },
    { name: "Moviedle - Fill The Grid", url: "https://moviedle.xyz/fill-the-grid", category: "Movies/TV" },
    { name: "Moviedle - Moviemoji", url: "https://moviedle.xyz/moviemoji", category: "Movies/TV" },
    { name: "Narutodle", url: "https://narutodle.net", category: "Movies/TV" },
    { name: "Onepiecedle", url: "https://onepiecedle.net", category: "Movies/TV" },
    { name: "Plotwords", url: "https://plotwords.com/daily", category: "Movies/TV" },
    { name: "Quolture", url: "https://www.quolture.com/#/", category: "Movies/TV" },
    { name: "Quotesed", url: "https://www.quotesed.com", category: "Movies/TV" },
    { name: "Showdle", url: "https://showdle.com", category: "Movies/TV" },
    { name: "Spongedle", url: "https://spongedle.onrender.com", category: "Movies/TV" },
    { name: "The Daily Burgle", url: "https://www.thedailyburgle.app", category: "Movies/TV" },
    { name: "TV Circuit", url: "https://www.wfhgames.com/tv-circuit", category: "Movies/TV" },
    { name: "Whodle", url: "https://whodle.dixonary.co.uk", category: "Movies/TV" },

    // Music
    { name: "Bandle", url: "https://bandle.app", category: "Music" },
    { name: "Beatdle", url: "https://beatdle.fun", category: "Music" },
    { name: "BopMatch", url: "https://bopmatch.com", category: "Music" },
    { name: "Crosstune", url: "https://crosstune.io", category: "Music" },
    { name: "Daily Jingle", url: "https://dailyjingle.me", category: "Music" },
    { name: "Disney Heardle", url: "https://www.disney.heardledecades.com", category: "Music" },
    { name: "Guess The Audio", url: "https://guesstheaudio.com", category: "Music" },
    { name: "Harmonies: Music Connections", url: "https://harmonies.io", category: "Music" },
    { name: "Heardle 1950's", url: "https://50s.heardledecades.com", category: "Music" },
    { name: "Heardle 1960's", url: "https://60s.heardledecades.com", category: "Music" },
    { name: "Heardle 1970's", url: "https://70s.heardledecades.com", category: "Music" },
    { name: "Heardle 1980's", url: "https://80s.heardledecades.com", category: "Music" },
    { name: "Heardle 1990's", url: "https://90s.heardledecades.com", category: "Music" },
    { name: "Heardle 2000's", url: "https://00s.heardledecades.com", category: "Music" },
    { name: "Heardle 2010's", url: "https://heardle10s.com", category: "Music" },
    { name: "Heardle 2020's", url: "https://20s.heardledecades.com", category: "Music" },
    { name: "Heardle Daily", url: "https://www.heardle.info/daily/", category: "Music" },
    { name: "Heardle K-pop", url: "https://kpop.heardledecades.com", category: "Music" },
    { name: "Heardle TV Themes", url: "https://tv.heardledecades.xyz", category: "Music" },
    { name: "Humppadle", url: "https://www.humppadle.de", category: "Music" },
    { name: "Lyricle", url: "https://www.lyricle.app", category: "Music" },
    { name: "MeloGuessr", url: "https://meloguessr.com", category: "Music" },
    { name: "Musicle", url: "https://musicle.app", category: "Music" },
    { name: "MusicVidle", url: "https://www.musicvidle.com", category: "Music" },
    { name: "Perfect Pitch Puzzle", url: "https://www.perfectpitchpuzzle.com", category: "Music" },
    { name: "ReHeardle", url: "https://reheardle.com", category: "Music" },
    { name: "ReHeardle Video Games", url: "https://reheardle.com/videogames", category: "Music" },
    { name: "relatle.io", url: "https://relatle.io", category: "Music" },
    { name: "Songdle", url: "https://statt-land-song.ch/songdle", category: "Music" },
    { name: "Songle", url: "https://histordle.com/songle", category: "Music" },
    { name: "Songless", url: "https://lessgames.com/songless", category: "Music" },
    { name: "SongSwipe", url: "https://play.songswipe.fun", category: "Music" },
    { name: "Spotle", url: "https://spotle.io", category: "Music" },
    { name: "Swiftle", url: "https://www.techyonic.co/swiftle", category: "Music" },
    { name: "TuneGuessr", url: "https://www.tuneguessr.net/", category: "Music" },
    { name: "Video Game Bandle", url: "https://www.vgbandle.app", category: "Music" },

    // Science/Nature
    { name: "Birdie Game", url: "https://birdiegame.net", category: "Science/Nature" },
    { name: "Birdle", url: "https://www.play-birdle.com", category: "Science/Nature" },
    { name: "Chemdle", url: "https://www.chemdle.com", category: "Science/Nature" },
    { name: "Disordle", url: "https://disordle.com", category: "Science/Nature" },
    { name: "Doctordle", url: "https://doctordle.org", category: "Science/Nature" },
    { name: "Doggle", url: "https://doggle.app", category: "Science/Nature" },
    { name: "Elemingle", url: "https://elemingle.com", category: "Science/Nature" },
    { name: "list animals until failure", url: "https://rose.systems/animalist/#today", category: "Science/Nature" },
    { name: "Metaflora", url: "https://flora.metazooa.com", category: "Science/Nature" },
    { name: "Metazooa", url: "https://metazooa.com", category: "Science/Nature" },
    { name: "Radiordle", url: "https://www.radiordle.org", category: "Science/Nature" },
    { name: "Stardle", url: "https://stardlegame.github.io/stardle", category: "Science/Nature" },
    { name: "Wildlife Sudoku", url: "https://flagdoku.com/wildlife.html", category: "Science/Nature" },

    // Shapes/Patterns
    { name: "Celtix", url: "https://www.andrewt.net/puzzles/celtix/", category: "Shapes/Patterns" },
    { name: "DayBrix", url: "https://vole.wtf/daybrix", category: "Shapes/Patterns" },
    { name: "Daydoku", url: "https://www.daydoku.com", category: "Shapes/Patterns" },
    { name: "FlashPopTiles", url: "https://flashpoptiles.com", category: "Shapes/Patterns" },
    { name: "Hidden Mirrors", url: "https://www.hidden-mirrors.com", category: "Shapes/Patterns" },
    { name: "Jigsaw Explorer", url: "https://www.jigsawexplorer.com", category: "Shapes/Patterns" },
    { name: "Jigsy", url: "https://jigsy.app", category: "Shapes/Patterns" },
    { name: "LA Times Jigsaw", url: "https://www.latimes.com/games/jigsaw-puzzle", category: "Shapes/Patterns" },
    { name: "LinkedIn - Zip", url: "https://www.linkedin.com/games/zip", category: "Shapes/Patterns" },
    { name: "LINKR", url: "https://www.playlinkr.net", category: "Shapes/Patterns" },
    { name: "Loopy", url: "https://loopy.wtf", category: "Shapes/Patterns" },
    { name: "Mazetangle", url: "https://mazetangle.com", category: "Shapes/Patterns" },
    { name: "Nerdcube - Carom", url: "https://www.nerdcube.games/carom", category: "Shapes/Patterns" },
    { name: "Netflix - Jigsaw", url: "https://www.netflix.com/tudum/puzzled/jigsaw/daily", category: "Shapes/Patterns" },
    { name: "Netflix - Shapes", url: "https://www.netflix.com/tudum/puzzled/shapes/daily", category: "Shapes/Patterns" },
    { name: "Nodes", url: "https://www.nodes-game.com", category: "Shapes/Patterns" },
    { name: "Number Crunch", url: "https://numbercrunch.fun", category: "Shapes/Patterns" },
    { name: "Puzzmo - Flipart", url: "https://www.puzzmo.com/play/flip-art", category: "Shapes/Patterns" },
    { name: "Rotaboxes", url: "https://rotaboxes.com", category: "Shapes/Patterns" },
    { name: "Rotatly", url: "https://www.rotatly.com", category: "Shapes/Patterns" },
    { name: "SetFury", url: "https://www.setfury.com", category: "Shapes/Patterns" },
    { name: "Shaple", url: "https://swag.github.io/shaple", category: "Shapes/Patterns" },
    { name: "Synthmaze", url: "https://synthmaze.heliante.io/#/daily", category: "Shapes/Patterns" },
    { name: "Triplets", url: "https://www.tripletgame.com", category: "Shapes/Patterns" },
    { name: "VideoPuzzle", url: "https://videopuzzle.org", category: "Shapes/Patterns" },

    // Novelty
    { name: "Coindle", url: "https://muhashi.com/coindle/", category: "Novelty" },
    { name: "Horsle", url: "https://cabletwo.net/horsle/", category: "Novelty" },
    { name: "Jeffgoldblumle", url: "https://jeffgoldblumle.vercel.app", category: "Novelty" },
    { name: "Luckle", url: "https://luckle.org", category: "Novelty" },
    { name: "RNGdle", url: "https://www.rngdle.com", category: "Novelty" },

    // Sports
    { name: "Basketball 5", url: "https://basketball-5.com", category: "Sports" },
    { name: "Batter Up", url: "https://www.batter-up.app", category: "Sports" },
    { name: "Chrono NBA", url: "https://chrono.quest/basketball.html", category: "Sports" },
    { name: "Chrono NFL", url: "https://chrono.quest/nfl.html", category: "Sports" },
    { name: "Daily Walkoff", url: "https://www.dailywalkoff.com", category: "Sports" },
    { name: "Factle Sports", url: "https://frontofficesports.com/trivia/factle-sports", category: "Sports" },
    { name: "Futbol 11", url: "https://futbol-11.com/", category: "Sports" },
    { name: "Futdoku", url: "https://flagdoku.com/futdoku.html", category: "Sports" },
    { name: "Hoopgrids", url: "https://www.hoopgrids.com", category: "Sports" },
    { name: "I Called Game", url: "https://icalledgame.hoopgrids.com", category: "Sports" },
    { name: "Immaculate Footy", url: "https://www.sports-reference.com/immaculate-footy/", category: "Sports" },
    { name: "Immaculate Grid: Baseball", url: "https://www.sports-reference.com/immaculate-grid/", category: "Sports" },
    { name: "Immaculate Grid: Hockey", url: "https://www.sports-reference.com/immaculate-grid/hockey", category: "Sports" },
    { name: "Immaculate Grid: Men's Basketball", url: "https://www.sports-reference.com/immaculate-grid/basketball/mens", category: "Sports" },
    { name: "Immaculate Grid: Pro Football", url: "https://www.sports-reference.com/immaculate-grid/football", category: "Sports" },
    { name: "Immaculate Grid: Women's Basketball", url: "https://www.sports-reference.com/immaculate-grid/basketball/womens", category: "Sports" },
    { name: "Mcbirdle", url: "https://kendisc.com/mcbirdle", category: "Sports" },
    { name: "MLB Pickle", url: "https://www.mlbpickle.com", category: "Sports" },
    { name: "NYT Connections: Sports Edition", url: "https://www.nytimes.com/athletic/connections-sports-edition", category: "Sports" },
    { name: "Poeltl", url: "https://poeltl.nbpa.com", category: "Sports" },
    { name: "Puckdoku", url: "https://www.puckdoku.com", category: "Sports" },
    { name: "StatPad Game", url: "https://www.statpadgame.com", category: "Sports" },
    { name: "Weddle", url: "https://www.weddlegame.com", category: "Sports" },
    { name: "Worpel", url: "https://playworpel.com", category: "Sports" },
    { name: "WrestlePlay", url: "https://wrestleplay.com", category: "Sports" },

    // Trivia
    { name: "Brainer", url: "https://gamebunny.app/brainer", category: "Trivia" },
    { name: "Catfishing", url: "https://catfishing.net", category: "Trivia" },
    { name: "Concludle", url: "https://tryhardguides.com/concludle", category: "Trivia" },
    { name: "Daily Dozen Trivia", url: "https://dailydozentrivia.com", category: "Trivia" },
    { name: "Daily Fact or Fiction", url: "https://dailyfactorfiction.com", category: "Trivia" },
    { name: "Daily Tens", url: "https://dailytens.com", category: "Trivia" },
    { name: "Disorderly", url: "https://playdisorderly.com", category: "Trivia" },
    { name: "Eruptle", url: "https://eruptle.app", category: "Trivia" },
    { name: "Factle", url: "https://frontofficesports.com/trivia/factle", category: "Trivia" },
    { name: "GuessTen", url: "https://guessten.com", category: "Trivia" },
    { name: "Jeopardy 6", url: "https://www.jeopardy.com/play/j6", category: "Trivia" },
    { name: "On the Record", url: "https://www.washingtonpost.com/news-quiz", category: "Trivia" },
    { name: "pedantle", url: "https://pedantle.certitudes.org", category: "Trivia" },
    { name: "PopCultured", url: "https://histordle.com/popcultured", category: "Trivia" },
    { name: "Quintalist", url: "https://www.quintalist.com", category: "Trivia" },
    { name: "Quizl", url: "https://quizl.io", category: "Trivia" },
    { name: "Rankle", url: "https://www.rankle.app", category: "Trivia" },
    { name: "Real Bird Fake Bird", url: "https://realbirdfakebird.com", category: "Trivia" },
    { name: "Redactle", url: "https://redactle.net", category: "Trivia" },
    { name: "Revealed", url: "https://www.britannica.com/games/revealed", category: "Trivia" },
    { name: "riddl.ing", url: "https://riddl.ing", category: "Trivia" },
    { name: "TED - Cheat Sheet", url: "https://www.ted.com/games/cheat-sheet", category: "Trivia" },
    { name: "The New Daily - Trivia", url: "https://www.thenewdaily.com.au/puzzles/quiz-trivia", category: "Trivia" },
    { name: "The Wiki Game Daily", url: "https://www.thewikigamedaily.com", category: "Trivia" },
    { name: "Thrice", url: "https://geekswhodrink.com/thrice", category: "Trivia" },
    { name: "Tightrope", url: "https://www.britannica.com/quiz/tightrope", category: "Trivia" },
    { name: "Top 5", url: "https://topfivetrivia.com", category: "Trivia" },

    // Vehicles
    { name: "Airport Guessr", url: "https://airportguessr.bytecatch.io/", category: "Vehicles" },
    { name: "Cardle", url: "https://cardle.boxbox.autos", category: "Vehicles" },
    { name: "CarGuesser", url: "https://carguesser.com", category: "Vehicles" },
    { name: "Planespottle", url: "https://planespottle.bytecatch.io", category: "Vehicles" },

    // Video Games
    { name: "Ace Attorneydle", url: "https://aceattorneydle.fr", category: "Video Games" },
    { name: "Balatrodle", url: "https://www.balatrodle.com", category: "Video Games" },
    { name: "Bazaar Doku", url: "https://bazaardb.gg/doku", category: "Video Games" },
    { name: "Bonedle", url: "https://bonedle.rito.lol", category: "Video Games" },
    { name: "Clasherdle", url: "https://clasherdle.pixelcrux.com/", category: "Video Games" },
    { name: "Craft Connections", url: "https://craftconnections.net", category: "Video Games" },
    { name: "Dotadle", url: "https://dotadle.net", category: "Video Games" },
    { name: "Emoji Quiz - Video Games", url: "https://www.emojiquiz.net/games", category: "Video Games" },
    { name: "Exodle", url: "https://exodle.astrelion.com", category: "Video Games" },
    { name: "Fortnitedle", url: "https://www.fortnitedle.net", category: "Video Games" },
    { name: "Framedle", url: "https://framedle.org", category: "Video Games" },
    { name: "Framedle.com", url: "https://framedle.com", category: "Video Games" },
    { name: "Gamedle Artwork", url: "https://www.gamedle.wtf/artwork", category: "Video Games" },
    { name: "Gamedle Character", url: "https://www.gamedle.wtf/characters", category: "Video Games" },
    { name: "Gamedle Classic", url: "https://www.gamedle.wtf/classic", category: "Video Games" },
    { name: "Gamedle Guess", url: "https://www.gamedle.wtf/guess", category: "Video Games" },
    { name: "Gamedle Keywords", url: "https://www.gamedle.wtf/keywords", category: "Video Games" },
    { name: "Genshindle", url: "https://us.genshindle.com/", category: "Video Games" },
    { name: "Guess The Game", url: "https://guessthe.game", category: "Video Games" },
    { name: "HOTSdle", url: "https://hotsdle.zgame.studio/", category: "Video Games" },
    { name: "HowLongToBeat Daily Challenge", url: "https://howlongtobeat.com/play", category: "Video Games" },
    { name: "Isaacle", url: "https://isaacle.net", category: "Video Games" },
    { name: "Isaaconnect", url: "https://isaaconnect.com", category: "Video Games" },
    { name: "Jingle.rs", url: "https://jingle.rs", category: "Video Games" },
    { name: "Lockle", url: "https://www.lockle.app", category: "Video Games" },
    { name: "LoLdle", url: "https://loldle.net", category: "Video Games" },
    { name: "MapleWordle", url: "https://www.maplewordle.com", category: "Video Games" },
    { name: "Marathondle", url: "https://marathondle.com", category: "Video Games" },
    { name: "Mcdle", url: "https://www.mcdle.net", category: "Video Games" },
    { name: "Minecraftle", url: "https://minecraftle.zachmanson.com", category: "Video Games" },
    { name: "Monster Hunter-dle", url: "https://monster-hunter-dle.akato.fr/classic", category: "Video Games" },
    { name: "Nookle", url: "https://nookle.net", category: "Video Games" },
    { name: "OWdle", url: "https://owdle.guessing.day", category: "Video Games" },
    { name: "Palwordle", url: "https://palwordle.net", category: "Video Games" },
    { name: "Pikadoku", url: "https://pikadoku.dentotino.com", category: "Video Games" },
    { name: "PokeCryptic", url: "https://www.pokecryptic.com", category: "Video Games" },
    { name: "Pokedle.com", url: "https://pokedle.com", category: "Video Games" },
    { name: "Pokedle.net", url: "https://pokedle.net", category: "Video Games" },
    { name: "Pokedoku", url: "https://pokedoku.com", category: "Video Games" },
    { name: "Pokegrid", url: "https://www.pokegrid.net", category: "Video Games" },
    { name: "Pokerating", url: "https://pokerating.com/puzzle", category: "Video Games" },
    { name: "Pufferdle", url: "https://pufferdle.com", category: "Video Games" },
    { name: "R6dle", url: "https://r6dle.net", category: "Video Games" },
    { name: "Raindle", url: "https://raindle.net/items", category: "Video Games" },
    { name: "Retro Game Trivia", url: "https://retrotrivia.games", category: "Video Games" },
    { name: "Rivadle", url: "https://rivadle.net", category: "Video Games" },
    { name: "Royaledle", url: "https://royaledle.com", category: "Video Games" },
    { name: "Runedle", url: "https://runedle.com", category: "Video Games" },
    { name: "Silksongdle", url: "https://silksongdle.com", category: "Video Games" },
    { name: "Smashdle", url: "https://smashdle.net", category: "Video Games" },
    { name: "Snapdle", url: "https://snapdle.github.io/classic", category: "Video Games" },
    { name: "Soulsborndle", url: "https://malthesers.github.io/soulsborndle", category: "Video Games" },
    { name: "Spiredle", url: "https://spiredle.com", category: "Video Games" },
    { name: "Squirdle Daily", url: "https://squirdle.fireblend.com/daily.html", category: "Video Games" },
    { name: "Stardewdle", url: "https://stardewdle.com/game", category: "Video Games" },
    { name: "steamdle.com", url: "https://steamdle.com", category: "Video Games" },
    { name: "Streetfighterdle", url: "https://streetfighterdle.net", category: "Video Games" },
    { name: "Tarkovdle", url: "https://tarkovdle.com", category: "Video Games" },
    { name: "Terradle", url: "https://www.terradle.com", category: "Video Games" },
    { name: "TF2dle", url: "https://www.tf2dle.com", category: "Video Games" },
    { name: "TFTdle", url: "https://tftdle.gg/classic", category: "Video Games" },
    { name: "Umadle", url: "https://umadle.net", category: "Video Games" },
    { name: "Valodle", url: "https://valodle.eu", category: "Video Games" },
    { name: "Wardle", url: "https://wardlegame.com/", category: "Video Games" },
    { name: "Weakdle", url: "https://dentotino.com/weakdle", category: "Video Games" },
    { name: "Weakdoku", url: "https://weakdoku.dentotino.com", category: "Video Games" },
    { name: "Wowdle", url: "https://www.wowdle.app", category: "Video Games" },
    { name: "Zeldadle", url: "https://www.zeldadle.net", category: "Video Games" },
    { name: "Zeldle", url: "https://zeldle.xyz", category: "Video Games" },
    { name: "ZoomOut", url: "https://zoomout.videoludid.com", category: "Video Games" },

    // Miscellaneous
    { name: "AITA Guesser", url: "https://muhashi.com/aita-guesser/", category: "Miscellaneous" },
    { name: "Am I Dead?", url: "https://www.amidead.gg", category: "Miscellaneous" },
    { name: "Archiguessr", url: "https://archiguesser.com", category: "Miscellaneous" },
    { name: "Artle", url: "https://www.nga.gov/artle.html", category: "Miscellaneous" },
    { name: "Baddle", url: "https://tumblecricket.net/Baddle/", category: "Miscellaneous" },
    { name: "Bibdle", url: "https://bibdle.com", category: "Miscellaneous" },
    { name: "Clue Tube", url: "https://thecluetube.com", category: "Miscellaneous" },
    { name: "Cosmeredle", url: "https://cosmeredle.net", category: "Miscellaneous" },
    { name: "Cropple", url: "https://cropple.app", category: "Miscellaneous" },
    { name: "Dungleon", url: "https://www.dungleon.com", category: "Miscellaneous" },
    { name: "enclose.horse", url: "https://enclose.horse", category: "Miscellaneous" },
    { name: "Face Guessr", url: "https://www.faceguesser.com", category: "Miscellaneous" },
    { name: "Facedle", url: "https://facedle.app", category: "Miscellaneous" },
    { name: "Forgeous", url: "https://forgeous.fun", category: "Miscellaneous" },
    { name: "graphs.world", url: "https://www.graphs.world", category: "Miscellaneous" },
    { name: "Guess The Book", url: "https://guessthebook.app", category: "Miscellaneous" },
    { name: "Guess The Logo", url: "https://guessthelogo.wtf", category: "Miscellaneous" },
    { name: "Kinda Hard Golf", url: "https://kindahardgolf.com", category: "Miscellaneous" },
    { name: "Minigolfle", url: "https://minigolfle.com", category: "Miscellaneous" },
    { name: "morsle", url: "https://morsle.fun", category: "Miscellaneous" },
    { name: "Morsle (decipher.wiki)", url: "https://decipher.wiki/morsle", category: "Miscellaneous" },
    { name: "Picsey", url: "https://picsey.io", category: "Miscellaneous" },
    { name: "Ponder Club", url: "https://ponderclub.co", category: "Miscellaneous" },
    { name: "Power Scadle", url: "https://powerscadle.com", category: "Miscellaneous" },
    { name: "Rogule", url: "https://rogule.com/game.html", category: "Miscellaneous" },
    { name: "Spot the differences", url: "https://www.spot-differences.com", category: "Miscellaneous" },
    { name: "Talldle", url: "https://www.talldle.com", category: "Miscellaneous" },
    { name: "The Daily Baffle", url: "https://dailybaffle.com", category: "Miscellaneous" },
    { name: "Thinky Dailies", url: "https://thinkygames.com/dailies/today/", category: "Miscellaneous" },
    { name: "Wallstreetle", url: "https://wallstreetle.com", category: "Miscellaneous" },
    { name: "Wantedle", url: "https://wantedle.com", category: "Miscellaneous" },
    { name: "Weather Darts", url: "https://www.weatherdarts.com", category: "Miscellaneous" },

    // Words
    { name: "23 Words", url: "https://wordnerd.co/23words", category: "Words" },
    { name: "7 Little Words", url: "https://7littlewords.com/7lw", category: "Words" },
    { name: "Absurdle", url: "https://qntm.org/files/absurdle/absurdle.html", category: "Words" },
    { name: "Adoptle", url: "https://tryhardguides.com/adoptle", category: "Words" },
    { name: "Alphalock", url: "https://alphalockgame.net", category: "Words" },
    { name: "Antiwordle", url: "https://www.antiwordle.com", category: "Words" },
    { name: "Betweenle", url: "https://betweenle.com", category: "Words" },
    { name: "Blockle", url: "https://blockle.au", category: "Words" },
    { name: "Blossom", url: "https://www.merriam-webster.com/games/blossom-word-game", category: "Words" },
    { name: "Blunderwall", url: "https://bythomas.co.uk/blunderwall", category: "Words" },
    { name: "Boggdle", url: "https://simenmh.com/boggdle", category: "Words" },
    { name: "Boston Globe - Align", url: "https://www.bostonglobe.com/games/align/", category: "Words" },
    { name: "Bracket City", url: "https://www.theatlantic.com/games/bracket-city/", category: "Words" },
    { name: "Cadgy", url: "https://onelook.com/cadgy/", category: "Words" },
    { name: "Categories", url: "https://categories.clevergoat.com", category: "Words" },
    { name: "Cell Tower", url: "https://www.andrewt.net/puzzles/cell-tower", category: "Words" },
    { name: "cemantle", url: "https://cemantle.certitudes.org", category: "Words" },
    { name: "Chainagram", url: "https://puzzletrail.games/puzzles/chainagram", category: "Words" },
    { name: "Chiddle", url: "https://www.chiddle.net", category: "Words" },
    { name: "CHN LNK", url: "https://thechnlnk.com", category: "Words" },
    { name: "ClickWord", url: "https://clickword.org", category: "Words" },
    { name: "Cluewords", url: "https://wordnerd.co/cluewords", category: "Words" },
    { name: "Cobble", url: "https://wilf.live/cobble/", category: "Words" },
    { name: "Codenames Daily", url: "https://codenames.game/daily/en", category: "Words" },
    { name: "Combinations", url: "https://combinations.org", category: "Words" },
    { name: "Compound Your Joy", url: "https://onelook.com/?loc=rd&w=cyj", category: "Words" },
    { name: "Conexo", url: "https://conexo.ws/en", category: "Words" },
    { name: "Connections Game", url: "https://connectionsgame.org", category: "Words" },
    { name: "Contexto", url: "https://contexto.me", category: "Words" },
    { name: "Couples", url: "https://www.couples.game", category: "Words" },
    { name: "Couplit", url: "https://couplit.io", category: "Words" },
    { name: "CraftWord", url: "https://craftword.game", category: "Words" },
    { name: "Crossflip", url: "https://puzzmallow.com/crossflip", category: "Words" },
    { name: "Crosshare", url: "https://crosshare.org", category: "Words" },
    { name: "Crossherd", url: "https://crossherd.clevergoat.com", category: "Words" },
    { name: "Crosslink", url: "https://romainpastureau.github.io/crosslink/", category: "Words" },
    { name: "Crossword Club Daily", url: "https://crosswordclub.com/puzzles/", category: "Words" },
    { name: "Crosswordle", url: "https://crosswordle.vercel.app", category: "Words" },
    { name: "crosswordle.com", url: "https://crosswordle.com", category: "Words" },
    { name: "crosswordle.org", url: "https://crosswordle.org", category: "Words" },
    { name: "cryptle", url: "https://cryptle.xyz", category: "Words" },
    { name: "Cyphr", url: "https://cyphrgame.com", category: "Words" },
    { name: "Daily Analogy", url: "https://dailyanalogy.com", category: "Words" },
    { name: "Daily Crypticle", url: "https://dailycrypticle.com", category: "Words" },
    { name: "Daily Fill-Ins", url: "https://azgames.io/game/daily-fill-ins", category: "Words" },
    { name: "Daily Gogen", url: "https://www.dailygogen.com", category: "Words" },
    { name: "Decipher", url: "https://decipher.wtf", category: "Words" },
    { name: "Decodex", url: "https://playdecodex.com", category: "Words" },
    { name: "Doople", url: "https://www.dooplepuzzle.com", category: "Words" },
    { name: "Dordle", url: "https://zaratustra.itch.io/dordle", category: "Words" },
    { name: "Duolock Game", url: "https://www.duolockgame.net", category: "Words" },
    { name: "Duotrigordle", url: "https://duotrigordle.com", category: "Words" },
    { name: "Eightile", url: "https://eightile.com", category: "Words" },
    { name: "Emoji Test", url: "https://emojitest.com/en", category: "Words" },
    { name: "Fibble", url: "https://fibble.xyz", category: "Words" },
    { name: "Flipple", url: "https://flipple.clevergoat.com", category: "Words" },
    { name: "Fluxis", url: "https://www.theatlantic.com/games/fluxis/", category: "Words" },
    { name: "Freestyle", url: "https://playfreestyle.co", category: "Words" },
    { name: "Fusele", url: "https://fusele.netlify.app/?daily", category: "Words" },
    { name: "Gisnep", url: "https://gisnep.com", category: "Words" },
    { name: "Glyph", url: "https://glyph.today", category: "Words" },
    { name: "Gram Jam", url: "https://gramjam.app", category: "Words" },
    { name: "Griddable", url: "https://griddable.co.uk", category: "Words" },
    { name: "Griddle", url: "https://griddlegame.io", category: "Words" },
    { name: "Gridogram", url: "https://www.gridogram.com", category: "Words" },
    { name: "Guess My Word", url: "https://hryanjones.com/guess-my-word", category: "Words" },
    { name: "Guess The Phrase", url: "https://guessthephrase.xyz", category: "Words" },
    { name: "hello wordl", url: "https://hellowordl.net/?today", category: "Words" },
    { name: "Huewords", url: "https://huewords.snellman.net", category: "Words" },
    { name: "Jumble Daily", url: "https://fun.chicagotribune.com/game/tca-jumble-daily/", category: "Words" },
    { name: "Jumblie", url: "https://jumblie.com", category: "Words" },
    { name: "Karat", url: "https://karat.auronymous.com", category: "Words" },
    { name: "Keyboard Lines", url: "https://keyboardlines.com", category: "Words" },
    { name: "Keyword", url: "https://www.washingtonpost.com/games/keyword", category: "Words" },
    { name: "LA Times Crossword", url: "https://www.latimes.com/games/daily-crossword", category: "Words" },
    { name: "LA Times Mini", url: "https://www.latimes.com/games/mini-crossword", category: "Words" },
    { name: "LA Times Word Search", url: "https://www.latimes.com/games/wordsearch", category: "Words" },
    { name: "LA Times Wordflower", url: "https://www.latimes.com/games/wordflower", category: "Words" },
    { name: "Langle", url: "https://langle.uk", category: "Words" },
    { name: "Letroso", url: "https://letroso.com/en/daily", category: "Words" },
    { name: "Lettered", url: "https://lettered.io", category: "Words" },
    { name: "Letteripher", url: "https://letteripher.com", category: "Words" },
    { name: "LetterLoop", url: "https://theletterloop.com", category: "Words" },
    { name: "Lex.Games - By A Vowel", url: "https://lex.games/byavowel/", category: "Words" },
    { name: "Lex.Games - Conlextions", url: "https://lex.games/connections/", category: "Words" },
    { name: "Lex.Games - Lexicogs", url: "https://lex.games/lexicogs/", category: "Words" },
    { name: "Lex.Games - Mini Crossword", url: "https://lex.games/mini/", category: "Words" },
    { name: "Lex.Games - Six Appeal", url: "https://lex.games/six/", category: "Words" },
    { name: "Lex.Games - Square Dance", url: "https://lex.games/squaredance", category: "Words" },
    { name: "Lexicle", url: "https://lexicle.com", category: "Words" },
    { name: "Lingule", url: "https://lingule.xyz", category: "Words" },
    { name: "LinkedIn - Crossclimb", url: "https://www.linkedin.com/games/crossclimb", category: "Words" },
    { name: "LinkedIn - Pinpoint", url: "https://www.linkedin.com/games/pinpoint", category: "Words" },
    { name: "Linxicon", url: "https://linxicon.com", category: "Words" },
    { name: "Lirdle", url: "https://lirdle.com", category: "Words" },
    { name: "Mini Crossword (The Observer)", url: "https://fordhamobserver.com/category/fun-and-games/daily-mini-crossword", category: "Words" },
    { name: "Minute Cryptic", url: "https://www.minutecryptic.com", category: "Words" },
    { name: "Mislettered", url: "https://tryhardguides.com/mislettered", category: "Words" },
    { name: "Nerdcube - Dabble", url: "https://www.nerdcube.games/dabble", category: "Words" },
    { name: "Netflix - Bonza", url: "https://www.netflix.com/tudum/puzzled/bonza/daily", category: "Words" },
    { name: "Netflix - Crossover", url: "https://www.netflix.com/tudum/puzzled/crossover/daily", category: "Words" },
    { name: "Netflix - Keysmash", url: "https://www.netflix.com/tudum/puzzled/keysmash/daily", category: "Words" },
    { name: "Netflix - Waywords", url: "https://www.netflix.com/tudum/puzzled/waywords/daily", category: "Words" },
    { name: "NYT Connections", url: "https://www.nytimes.com/games/connections", category: "Words" },
    { name: "NYT Strands", url: "https://www.nytimes.com/games/strands", category: "Words" },
    { name: "NYT Wordle", url: "https://www.nytimes.com/games/wordle/index.html", category: "Words" },
    { name: "Octordle", url: "https://www.britannica.com/games/octordle", category: "Words" },
    { name: "Omiword", url: "https://www.omiword.com", category: "Words" },
    { name: "One Word Search", url: "https://puzzlist.com/onewordsearch/", category: "Words" },
    { name: "Orbits", url: "https://www.playorbits.com", category: "Words" },
    { name: "Pair Down", url: "https://pairdown.com", category: "Words" },
    { name: "Parseword", url: "https://www.parseword.com", category: "Words" },
    { name: "Phrasicle", url: "https://phrasicle.com", category: "Words" },
    { name: "Phrasle", url: "https://phrasle.com", category: "Words" },
    { name: "Pimantle", url: "https://semantle.pimanrul.es", category: "Words" },
    { name: "PIVOT", url: "https://pivotthegame.com", category: "Words" },
    { name: "Pixletters", url: "https://pixletters.com", category: "Words" },
    { name: "Plausible", url: "https://plausiblegame.com/en", category: "Words" },
    { name: "Pocket Puzzles", url: "https://playpocketpuzzles.com", category: "Words" },
    { name: "Polygonle", url: "https://www.polygonle.com", category: "Words" },
    { name: "Poople", url: "https://poople.io", category: "Words" },
    { name: "Puzzmo - Bongo", url: "https://www.puzzmo.com/game/bongo", category: "Words" },
    { name: "Puzzmo - Circuits", url: "https://www.puzzmo.com/play/circuits", category: "Words" },
    { name: "Puzzmo - Crossword", url: "https://www.puzzmo.com/play/crossword", category: "Words" },
    { name: "Puzzmo - Spelltower", url: "https://www.puzzmo.com/play/spelltower", category: "Words" },
    { name: "Puzzmo - Typeshift", url: "https://www.puzzmo.com/play/typeshift", category: "Words" },
    { name: "Quickflip", url: "https://puzzmallow.com/quickflip", category: "Words" },
    { name: "Quintessential", url: "https://quintessential.fun", category: "Words" },
    { name: "Quizl", url: "https://quizl.io", category: "Words" },
    { name: "Quordle", url: "https://www.merriam-webster.com/games/quordle/#/", category: "Words" },
    { name: "RADDLE", url: "https://raddle.quest", category: "Words" },
    { name: "Redividers", url: "https://redividers.netlify.app", category: "Words" },
    { name: "regexle.ithea.de", url: "https://regexle.ithea.de", category: "Words" },
    { name: "Relatle", url: "https://www.relatle.lol", category: "Words" },
    { name: "Reversle", url: "https://reversle.net", category: "Words" },
    { name: "Rewordio", url: "https://rewordio.com", category: "Words" },
    { name: "Rhyme Time", url: "https://www.rhymetime.co", category: "Words" },
    { name: "Scramble", url: "https://playscramble.vercel.app/?daily=1", category: "Words" },
    { name: "Searchle", url: "https://searchle.net", category: "Words" },
    { name: "sedecordle", url: "https://sedecordle.com", category: "Words" },
    { name: "Semantle", url: "https://semantle.com", category: "Words" },
    { name: "Sexaginta-quattuordle", url: "https://64ordle.au/?mode=daily", category: "Words" },
    { name: "Shrinkle", url: "https://shrinkle.org", category: "Words" },
    { name: "Shuffalo", url: "https://www.newyorker.com/puzzles-and-games-dept/shuffalo", category: "Words" },
    { name: "Silly Little Codes", url: "https://playsillylittlegames.com/codes", category: "Words" },
    { name: "Slate - Pears", url: "https://slate.com/games/pears", category: "Words" },
    { name: "Smixed", url: "https://smixed.com", category: "Words" },
    { name: "Sortdle", url: "https://sortdle.com", category: "Words" },
    { name: "SpaceWord", url: "https://spaceword.org", category: "Words" },
    { name: "Spell Bee", url: "https://www.spell-bee.com/game-daily.html", category: "Words" },
    { name: "Spellcheck", url: "https://spellcheck.xyz", category: "Words" },
    { name: "Spellie", url: "https://spelliegame.com", category: "Words" },
    { name: "Spelling Bee", url: "https://spellsbee.com", category: "Words" },
    { name: "Spelling Bee (Lessgames)", url: "https://lessgames.com/spellingbee", category: "Words" },
    { name: "Spindle", url: "https://playspindle.com", category: "Words" },
    { name: "Sporcle Daily Acrostic", url: "https://www.sporcle.com/acrostic/todays-acrostic", category: "Words" },
    { name: "Squardle", url: "https://fubargames.se/squardle", category: "Words" },
    { name: "Squaredle", url: "https://squaredle.app", category: "Words" },
    { name: "Squares", url: "https://squares.org", category: "Words" },
    { name: "Squareword", url: "https://squareword.org", category: "Words" },
    { name: "Squeezy", url: "https://imsqueezy.com", category: "Words" },
    { name: "Stackdown", url: "https://puzzlist.com/stackdown/", category: "Words" },
    { name: "Stacked", url: "https://stacked.clevergoat.com", category: "Words" },
    { name: "Stackle", url: "https://www.stackle.fun", category: "Words" },
    { name: "Stacks", url: "https://www.theatlantic.com/games/stacks/", category: "Words" },
    { name: "Stat Mini Crossword", url: "https://www.statnews.com/stat-mini-crossword/", category: "Words" },
    { name: "Stepwords", url: "https://stepwords.xyz", category: "Words" },
    { name: "Summit Game", url: "https://summit-puzzle.me", category: "Words" },
    { name: "Survivle", url: "https://lazyguyy.github.io/survivle", category: "Words" },
    { name: "Swapple", url: "https://nibble.games/swapple/swapple-easy.html", category: "Words" },
    { name: "Symble", url: "https://www.symble.app", category: "Words" },
    { name: "TED - Letterbrew", url: "https://www.ted.com/games/letter-brew", category: "Words" },
    { name: "TED - Spellcheck", url: "https://www.ted.com/games/spellcheck", category: "Words" },
    { name: "The Atlantic Crossword", url: "https://www.theatlantic.com/games/daily-crossword/", category: "Words" },
    { name: "The Daily Spell", url: "https://www.the-daily-spell.com", category: "Words" },
    { name: "The Guardian - Cryptic Crossword", url: "https://www.theguardian.com/crosswords/series/cryptic", category: "Words" },
    { name: "The Guardian - Quick Crossword", url: "https://www.theguardian.com/crosswords/series/quick", category: "Words" },
    { name: "Thirdle", url: "https://thirdle.org", category: "Words" },
    { name: "Three Magic Words", url: "https://www.threemagicwords.app/play", category: "Words" },
    { name: "Threepeat", url: "https://onelook.com/threepeat", category: "Words" },
    { name: "Tiled Words", url: "https://tiledwords.com", category: "Words" },
    { name: "Tiler", url: "https://gamebunny.app/tiler", category: "Words" },
    { name: "Toddle", url: "https://toddle-puzzle.web.app", category: "Words" },
    { name: "Totem Words", url: "https://totemwords.com", category: "Words" },
    { name: "Tracell", url: "https://tracellgame.com", category: "Words" },
    { name: "Traindle", url: "https://www.traindle.io", category: "Words" },
    { name: "trms", url: "https://impliedampersand.itch.io/trms", category: "Words" },
    { name: "Truncate", url: "https://truncate.town", category: "Words" },
    { name: "Unolingo", url: "https://games.usatoday.com/games/uclick-unolingo", category: "Words" },
    { name: "Verticle", url: "https://verticle.netlify.app", category: "Words" },
    { name: "Vowel Play", url: "https://bythomas.co.uk/vowelplay", category: "Words" },
    { name: "Vox Daily Crossword", url: "https://www.vox.com/21523212/crossword-puzzles-free-daily-printable", category: "Words" },
    { name: "Waffle", url: "https://wafflegame.net/daily", category: "Words" },
    { name: "Washington Post Crossword", url: "https://www.washingtonpost.com/games/crossword/", category: "Words" },
    { name: "Weaver", url: "https://weavergame.org", category: "Words" },
    { name: "werdel", url: "https://bennw.github.io/werdel/#daily", category: "Words" },
    { name: "Worchle", url: "https://www.worchle.com", category: "Words" },
    { name: "Word Box", url: "https://wordbox.game", category: "Words" },
    { name: "Word Chain", url: "https://wordnerd.co/wordchain", category: "Words" },
    { name: "Word Chase", url: "https://wordchase.semantle.com", category: "Words" },
    { name: "Word Connection", url: "https://www.thewordfinder.com/word-connection", category: "Words" },
    { name: "Word Grid", url: "https://wordgrid.clevergoat.com", category: "Words" },
    { name: "Word Ladder", url: "https://wordladder.com", category: "Words" },
    { name: "Word Peaks", url: "https://vegeta897.github.io/word-peaks", category: "Words" },
    { name: "Word Salad", url: "https://wordsalad.online", category: "Words" },
    { name: "Word to your Mother", url: "https://w2ym.org", category: "Words" },
    { name: "Word Waffle", url: "https://wordwaffle.org", category: "Words" },
    { name: "Word Zip", url: "https://www.wfhgames.com/word-zip", category: "Words" },
    { name: "word.golf", url: "https://word.golf", category: "Words" },
    { name: "Word500", url: "https://word500.com/game?mode=daily", category: "Words" },
    { name: "WordAll", url: "https://wordall.xyz", category: "Words" },
    { name: "Wordamid", url: "https://www.wordamid.com", category: "Words" },
    { name: "Wordcell", url: "https://gamebunny.app/wordcell", category: "Words" },
    { name: "Wordcrux", url: "https://wordcrux.com", category: "Words" },
    { name: "Wordfall", url: "https://play-wordfall.com", category: "Words" },
    { name: "Wordga", url: "https://wordga.com/daily", category: "Words" },
    { name: "Wordgy", url: "https://wordgy.com", category: "Words" },
    { name: "Wordiply", url: "https://www.wordiply.com", category: "Words" },
    { name: "Wordistance", url: "https://wordistance.com", category: "Words" },
    { name: "Wordless", url: "https://lessgames.com/wordless", category: "Words" },
    { name: "WordLink", url: "https://playwordlink.com", category: "Words" },
    { name: "Wordloop", url: "https://word-loop.com", category: "Words" },
    { name: "words for days", url: "https://wordsfordays.com", category: "Words" },
    { name: "WordSmyth", url: "https://playwordsmyth.com", category: "Words" },
    { name: "Wordspan", url: "https://puzzmallow.com/wordspan", category: "Words" },
    { name: "WordWavr", url: "https://wordwavr.app", category: "Words" },
    { name: "Wormle", url: "https://wormle.com", category: "Words" },
    { name: "WRDLINK", url: "https://www.wrdlink.io", category: "Words" },
    { name: "Wridges", url: "https://www.washingtonpost.com/games/wridges/", category: "Words" },
    { name: "Wrodeo", url: "https://wrodeo.com", category: "Words" },
];